# Generated by Django 4.2.3 on 2023-07-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IAMUser",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallet.iamuser"
                    ),
                ),
            ],
        ),
    ]
