# Generated by Django 4.2.3 on 2023-07-15 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("payee", models.CharField(max_length=100, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.category",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget", models.IntegerField()),
                ("date_month", models.PositiveIntegerField(default=7)),
                ("date_year", models.PositiveIntegerField(default=2023)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.category",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "date_month", "date_year", "user_id")},
            },
        ),
    ]
