# Generated by Django 4.2.3 on 2023-07-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iamuser",
            name="password",
        ),
    ]
