# Generated by Django 4.2.3 on 2023-07-13 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_record_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 13, 12, 35, 0, 71644)
            ),
        ),
    ]
