# Generated by Django 4.2.3 on 2023-07-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_record_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iamuser",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
