# Generated by Django 4.2.3 on 2023-07-13 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_alter_record_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="payee",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 13, 13, 17, 4, 884393)
            ),
        ),
    ]
